import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import Topbar from '@/components/nav/Topbar';
import { SearchContextProvider } from '@/context/SearchContext';
import { CountryContextProvider } from '@/context/CountryContext';
import { CategoryContextProvider } from '@/context/CategoryContext';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'News App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <SearchContextProvider>
        <CountryContextProvider>
          <CategoryContextProvider>
            <body className={`${inter.className}`}>
              <Topbar />
              {children}
            </body>
          </CategoryContextProvider>
        </CountryContextProvider>
      </SearchContextProvider>
    </html>
  );
}
